# Generated by Django 3.0.5 on 2020-06-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(max_length=255, verbose_name='Short name')),
            ],
            options={
                'verbose_name': 'measure unit',
                'verbose_name_plural': 'measure units',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MeasureUnitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('units', models.ManyToManyField(related_name='groups', to='ingredient.MeasureUnit')),
            ],
            options={
                'verbose_name': 'grupo de unidades',
                'verbose_name_plural': 'grupos de unidades',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('unit_groups', models.ManyToManyField(blank=True, to='ingredient.MeasureUnitGroup')),
                ('units', models.ManyToManyField(blank=True, to='ingredient.MeasureUnit')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
                'ordering': ('name',),
            },
        ),
    ]
